### ISSUE TITLE
Punto de vista de la solucion

### ISSUE THREAD

**Issue by semurat** [fermarja/t2_life#2]
Siempre esta Kata tiene dos posibles soluciones que he visto en distintos Code Retreats en que he participado (lo que os dije de juntarse un dia (https://www.coderetreat.org/events/) para resolver esta kata en iteraciones de 45 minutos cambiando de parejas, haciendo pair programming y con distintas restricciones en cada iteracion de desarrollo.

Una de ellas es hacerlo desde el punto de vista del tablero y el otro es hacerlo desde el punto de vista de la celula.

En estos ejercicios no hay solucion buena o mala, tomes la que tomes es avanzar en descubrir todos los limites de la misma y ver como lo abordamos o resolvemos.

Si lo ahces desde el punto de vista de la celula, es ella quien sabe cuantas vecinas tiene en que estado (vivas o muertas) y eso hace que pueda evolucionar a la vida o a la muete o seguir como estaba segun el caso. Con ese enfoque podemos perder la vision de el mundo, esa seria la segunda parte, meter las celulas en ese Universo y ver como van madurando dentro de el.

El otro enfoque es el que has planteado, tenemos el Universo o tablero y vemos ante las celulas que hay lo que pasa con una de ellas. 

https://github.com/fermarja/t2_life/blob/3aa92f459710133279896ed5123feecaad47587f/src/main/java/es/jcyl/cag/cursotesting/life/Life.java#L26

**Comment by fermarja** [comment]
Hacerlo asi es mas pensando en su visualizacion en pantalla, que es mas directo.
Gracias
